ALTER TABLE store_settings
ADD COLUMN IF NOT EXISTS accept_online_pix BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS accept_online_card BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS accept_delivery_pix BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS accept_delivery_card BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS accept_delivery_cash BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(20) NOT NULL DEFAULT 'online';

UPDATE orders
SET payment_mode = 'delivery'
WHERE payment_method = 'cash';
